# Generated by Django 4.2.1 on 2023-07-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=40, null=True)),
                ('message', models.TextField()),
                ('message_time', models.DateTimeField()),
            ],
        ),
    ]
