# Generated by Django 4.2.1 on 2023-06-27 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('other_names', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('id_card_number', models.CharField(max_length=10)),
                ('capacity', models.CharField(choices=[('writer', 'Writer Journalist'), ('photojournalist', 'Photo Journalist'), ('editor', 'Editor'), ('director', 'Director')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile_pictures')),
                ('email', models.EmailField(max_length=254)),
                ('id_card_number', models.CharField(max_length=10)),
                ('capacity', models.CharField(choices=[('writer', 'Writer Journalist'), ('photojournalist', 'Photo Journalist'), ('editor', 'Editor'), ('director', 'Director')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
