# Generated by Django 4.2.1 on 2023-07-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bioline',
            field=models.TextField(null=True),
        ),
    ]
