# Generated by Django 4.2.1 on 2023-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_picture_journalist_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_card_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
