# Generated by Django 4.2.1 on 2023-07-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_reviews_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
