# Generated by Django 4.2.1 on 2023-06-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_project_status_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='end_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
