# Generated by Django 4.2.1 on 2023-06-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_project_end_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_of_creation',
            field=models.DateTimeField(null=True),
        ),
    ]
