# Generated by Django 4.2.1 on 2023-07-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_click'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='time_date',
            new_name='date',
        ),
    ]
