# Generated by Django 4.2.1 on 2023-07-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_usernotification_tasknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknotification',
            name='current_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
