# Generated by Django 4.2.1 on 2023-07-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_tasknotification_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_date_time',
        ),
    ]
