# Generated by Django 4.2.1 on 2023-07-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_task_end_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
