# Generated by Django 4.2.1 on 2023-07-03 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_id_card_number'),
        ('pages', '0012_task_end_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtext',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='subtext',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='submision_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20),
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_text', models.TextField(null=True)),
                ('submision_status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_section', to='pages.article')),
                ('journalist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journalist', to='users.journalist')),
            ],
        ),
    ]
