# Generated by Django 4.2.1 on 2023-07-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_article_subtext_article_title_photogallery_subtext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknotification',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('danger', 'Danger'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
