# Generated by Django 4.2.1 on 2023-07-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_tasknotification_type_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedTitleSubText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtext', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='proposed_title_subtext',
            field=models.ManyToManyField(related_name='proposed_title_subtext', to='pages.proposedtitlesubtext'),
        ),
    ]
