# Generated by Django 4.2.1 on 2023-07-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_proposedtitlesubtext_article_proposed_title_subtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesection',
            name='section_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
