# Generated by Django 4.2.1 on 2023-07-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_id_card_number'),
        ('pages', '0016_articlesection_section_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasknotification',
            old_name='created_at',
            new_name='creation_time',
        ),
        migrations.AddField(
            model_name='proposedtitlesubtext',
            name='journalist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.journalist'),
        ),
    ]
