# Generated by Django 4.2.1 on 2023-07-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rename_created_at_tasknotification_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknotification',
            name='creation_time',
            field=models.DateTimeField(null=True),
        ),
    ]
