# Generated by Django 4.2.1 on 2023-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_tasknotification_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proposedtitlesubtext',
            name='subtext',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='proposedtitlesubtext',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
