# Generated by Django 4.2.1 on 2023-07-03 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_id_card_number'),
        ('pages', '0019_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='journalist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_journalist', to='users.journalist'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='submision_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20),
        ),
    ]
