# Generated by Django 4.2.1 on 2023-07-03 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_photogallery_journalist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesection',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_sections', to='pages.article'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_gallery', to='pages.task'),
        ),
    ]
