# Generated by Django 4.2.1 on 2023-07-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_articlesection_article_alter_photogallery_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_gallery', to='pages.task'),
        ),
    ]
