# Generated by Django 4.2.1 on 2023-07-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_photogallery_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='proposed_title_subtext',
        ),
        migrations.AddField(
            model_name='proposedtitlesubtext',
            name='article',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='pages.article'),
            preserve_default='true',
        ),
    ]
