# Generated by Django 4.2.1 on 2023-07-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_article_proposed_title_subtext_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='submision_status',
            new_name='submission_status',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
