# Generated by Django 4.2.1 on 2023-07-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_rename_submision_status_task_submission_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesection',
            old_name='submision_status',
            new_name='submission_status',
        ),
        migrations.RenameField(
            model_name='photogallery',
            old_name='submision_status',
            new_name='submission_status',
        ),
    ]
