# Generated by Django 4.2.1 on 2023-07-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_rename_submision_status_articlesection_submission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtext',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='section_title',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
