# Generated by Django 4.2.1 on 2023-07-05 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='task',
        ),
        migrations.AddField(
            model_name='photogallery',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_gallery', to='pages.article'),
        ),
    ]
