# Generated by Django 4.2.1 on 2023-07-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_remove_photogallery_task_photogallery_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='photo_gallery'),
        ),
    ]
