# Generated by Django 4.2.1 on 2023-07-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='type',
            field=models.CharField(default='original', max_length=10),
        ),
    ]
