# Generated by Django 4.2.1 on 2023-07-06 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_instruction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRejections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_rejections', to='pages.task')),
            ],
        ),
        migrations.CreateModel(
            name='SectionRejections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('article_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_rejections', to='pages.articlesection')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryRejections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('photo_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_rejections', to='pages.photogallery')),
            ],
        ),
    ]
