# Generated by Django 4.2.1 on 2023-07-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_taskrejections_sectionrejections_galleryrejections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo_gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_gallery', to='pages.photogallery'),
        ),
    ]
