# Generated by Django 4.2.1 on 2023-07-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_alter_image_photo_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='publication_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='submission_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='submission_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20),
        ),
    ]
