# Generated by Django 4.2.1 on 2023-07-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_tags_reviews_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_date',
            field=models.DateTimeField(null=True),
        ),
    ]
