# Generated by Django 4.2.1 on 2023-07-07 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_id_card_number'),
        ('pages', '0038_reviews_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesection',
            name='journalist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalist', to='users.journalist'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='journalist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_journalist', to='users.journalist'),
        ),
    ]
